### ISSUE TITLE
readme review

### ISSUE THREAD

**Issue by heathervant** [sjackman/talr#2]
Good structure of readme and links for background info. 
- [x] Would still appreciate a few sentences explaining what linked reads are, to give more context.
- [x] Try to explain abbreviations before using them... like NG50 and chr4
- [x] please explain what Unicycler and bandage are and why you chose to use them.
- [x]  also give credit to those other package repos  when credit is due.
- [x] Doesn't hurt to add a CONDUCT.md file to explain how you would like people to contribute to the repo. :) https://github.com/sjackman/talr/pull/4

excited to see your results!

**Comment by sjackman** [comment]
Thank you for the review, Heather!

**Comment by sjackman** [comment]
Done. Thanks again, Heather!
